package com.test_vocacional.constant;

public class AptitudesConstants {

    public AptitudesConstants() {
    }

    public static final String[] PREGUNTAS = {
            "1. Tratar y hablar con sensibilidad a las personas.",
            "2. Ser jefe competente de un grupo, equipo o sociedad.",
            "3. Expresarte con facilidad en clase o al platicar con tus amigos.",
            "4. Dibujar casar, objetos, figuras humanas, etcétera.",
            "5. Cantar en un grupo.",
            "6. Llevar en forma correcta y ordenada los apuntes de clase. ",
            "7. Entender principios y experimentos de biología.",
            "8. Ejecutar con rapidez y exactitud operaciones aritméticas.",
            "9. Armar y componer objetos mecánicos como chapas,timbres,etcétera.",
            "10. Actividades que requieren destreza manual.",
            "11. Ser miembro activo y útil en un club o sociedad.",
            "12. Organizar y dirigir festivales, encuentros deportivos, excursiones o campañas sociales.",
            "13. Redactar composiciones o artículos periodísticos.",
            "14. Pintar paisajes.",
            "15. Tocar un instrumento musical.",
            "16. Ordenar y clasificar debidamente documentos en una oficina.",
            "17. Entender principios y experimentos de física.",
            "18. Resolver problemas de aritmética.",
            "19. Desarmar, armar y componer objetos complicados.",
            "20. Manejar con habilidad herramienta de carpintería.",
            "21. Colaborar con otros para el bien de la comunidad.",
            "22. Convencer a otros para que hagan lo que crees que deben hacer.",
            "23. Componer versos serios o jocosos.",
            "24. Decorar artísticamente un salón, corredor, escenario o patio para un festival.",
            "25. Distinguir cuando alguien desentona en las canciones o piezas musicales.",
            "26. Contestar y redactar correctamente oficios y cartas.",
            "27. Entender principios y experimentos de química.",
            "28. Resolver rompecabezas numéricos.",
            "29. Resolver rompecabezas de alambre o de madera.",
            "30. Manejar con facilidad herramientas mecánicas como pinzas, llaves de tuercas, desarmador, etcétera.",
            "31. Saber escuchar a otros con paciencia y comprender su punto de vista.",
            "32. Dar órdenes a otros con seguridad y naturalidad.",
            "33. Escribir cuentos, narraciones o historietas.",
            "34. Modelar con barro, plastilina o grabar madera.",
            "35. Entonar correctamente las canciones de moda.",
            "36. Anotar y manejar con exactitud y rapidez nombres, números y otros datos.",
            "37. Entender principios y hechos económicos y sociales.",
            "38. Resolver problemas de álgebra.",
            "39. Armar y componer muebles.",
            "40. Manejar con habilidad pequeñas piezas y herramientas como agujas, manecillas, joyas, piezas de relojería, etcétera.",
            "41. Conversar en las reuniones y fiestas con acierto y naturalidad.",
            "42. Dirigir un grupo o equipo en situaciones difíciles o peligrosas.",
            "43. Distinguir y apreciar la buena literatura.",
            "44. Distinguir y apreciar la buena pintura.",
            "45. Distinguir y apreciar la buena música.",
            "46. Encargarse de recibir, anotar y dar recados sin olvidar detalles importantes.",
            "47. Entender las causas que determinan los acontecimientos históricos.",
            "48. Resolver problemas de geometría.",
            "49. Aprender el funcionamiento de ciertos mecanismos complicados como motores, relojes, bombas, etcétera.",
            "50. Hacer con facilidad trazos geométricos con la ayudad de las escuadras, la regla “T” y compás.",
            "51. Actuar con desinterés.",
            "52. Corregir a los demás sin ofenderlos.",
            "53. Exponer juicios públicamente sin preocupación por la crítica.",
            "54. Colaborar en la elaboración de un libro sobre el arte en la Arquitectura.",
            "55. Dirigir un grupo musical.",
            "56. Colaborar en el desarrollo de métodos más eficientes de trabajo.",
            "57. Realizar investigaciones científicas teniendo como finalidad la búsqueda de la verdad.",
            "58. Enseñar a resolver problemas de matemáticas.",
            "59. Inducir a las personas a obtener resultados prácticos.",
            "60. Participar en un concurso de modelismo de coches, aviones, barcos, etcétera."
    };
}
