package com.test_vocacional.constant;

public class InteresesConstants {

    public InteresesConstants() {
    }

    public static final String[] PREGUNTAS = {
            "1. Atender y cuidar enfermos",
            "2. Intervenir activamente en las discusiones de clase.",
            "3. Escribir cuentos, crónicas o artículos.",
            "4. Dibujar y pintar.",
            "5. Cantar en un coro estudiantil.",
            "6. Llevar en orden tus libros y cuadernos.",
            "7. Conocer y estudiar la estructura de las plantas y de los animales.",
            "8. Resolver cuestionarios de matemáticas.",
            "9. Armar y desarmar objetos mecánicos.",
            "10. Salir de excursión.",
            "11. Proteger a los muchachos menores del grupo.",
            "12. Ser jefe de un grupo.",
            "13. Leer obras literarias.",
            "14. Moldear el barro, plastilina o cualquier otro material.",
            "15. Escuchar música clásica.",
            "16. Ordenar y clasificar los libros de una biblioteca.",
            "17. Hacer experimentos en un laboratorio.",
            "18. Resolver problemas de aritmética.",
            "19. Manejar herramientas y maquinaria.",
            "20. Pertenecer a un grupo de exploradores.",
            "21. Ser miembro de una sociedad de ayuda y asistencia.",
            "22. Dirigir la campaña política para un candidato estudiantil.",
            "23. Hacer versos para una publicación.",
            "24. Encargarte del decorado del lugar para un festival.",
            "25. Aprender a tocar un instrumento musical.",
            "26. Aprender a escribir a máquina y en taquigrafía.",
            "27. Investigar el origen de las costumbres de los pueblos.",
            "28. Llevar las cuentas de una institución.",
            "29. Construir objeto o muebles.",
            "30. Trabajar al aire libre, fuera de la ciudad.",
            "31. Enseñar a leer a los analfabetos.",
            "32. Hacer propaganda para la difusión de una idea.",
            "33. Representar un papel en una obra de teatro.",
            "34. Idear y diseñar el escudo de un club o sociedad.",
            "35. Ser miembro de una asociación musical.",
            "36. Ayudar a calificar pruebas.",
            "37. Estudiar y entender las causas de los movimientos sociales.",
            "38. Explicar a otros cómo resolver problemas de matemáticas.",
            "39. Reparar las instalaciones eléctricas, de gas o de plomería en tu casa.",
            "40. Sembrar y plantar en una granja durante las vacaciones.",
            "41. Ayudar a tus compañeros en sus dificultades y preocupaciones.",
            "42. Leer biografías de políticos eminentes.",
            "43. Participar en un concurso de oratoria.",
            "44. Diseñar el vestuario para una función teatral.",
            "45. Leer biografías de músicos eminentes.",
            "46. Encargarte del archivo y los documentos de una sociedad.",
            "47. Leer revistas y libros científicos.",
            "48. Participar en concursos de matemáticas.",
            "49. Proyectar y dirigir alguna construcción.",
            "50. Atender animales en un rancho durante las vacaciones.",
            "51. ¿Qué tanto te gustaría trabajar como? Funcionario al servicio de las clases humildes.",
            "52. ¿Qué tanto te gustaría trabajar como? Experto en relaciones sociales de una gran empresa.",
            "53. ¿Qué tanto te gustaría trabajar como? Escritor en un periódico o empresa editorial.",
            "54. ¿Qué tanto te gustaría trabajar como? Dibujante profesional en una empresa.",
            "55. ¿Qué tanto te gustaría trabajar como? Concertista en una sinfónica.",
            "56. ¿Qué tanto te gustaría trabajar como? Técnico organizador de oficinas.",
            "57. ¿Qué tanto te gustaría trabajar como? Investigar en un laboratorio.",
            "58. ¿Qué tanto te gustaría trabajar como? Experto calculista en una institución.",
            "59. ¿Qué tanto te gustaría trabajar como? Perito mecánico en un taller.",
            "60. ¿Qué tanto te gustaría trabajar como? Técnico cuyas actividades se desempeñan fuera de la ciudad."
    };
}
